function sma_out = AddConfigStates(sma, namestr, stateName, conditionstr, stateChangeConditions, outputstr, outputActions, ~, maxDrivenRPM, ~, timeMultiplier, ~, tolerance, ~, encoderPPR, ~, maxRotation, ~, correctiveSpeedDegreesPerSecond, ~, correctiveKd, ~, correctiveEnable, ~, correctionStartDelayMs)

global ServoMotorStruct

servoMotor = 'ServoMotor1';
configOpCode = uint8(254);
receivedInstruction = 'ServoMotor1_2';
configGainScale = 1000;
kDegreesPerSecondPerRPM = 6;
kFirmwareCorrectiveSpeedScale = kDegreesPerSecondPerRPM;


validateattributes(maxDrivenRPM, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'positive', '<=', double(intmax('uint16'))}, ...
    mfilename, 'maxDrivenRPM');
validateattributes(timeMultiplier, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'positive', '<=', double(intmax('uint16'))}, ...
    mfilename, 'timeMultiplier');
validateattributes(tolerance, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'nonnegative', '<=', double(intmax('uint16'))}, ...
    mfilename, 'tolerance');
validateattributes(encoderPPR, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'positive', '<=', double(intmax('uint16'))}, ...
    mfilename, 'encoderPPR');

% maxRotation is transmitted as uint16 degrees. The firmware converts it
% to quadrature encoder ticks using the configured encoderPPR.
validateattributes(maxRotation, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'positive', '<=', double(intmax('uint16'))}, ...
    mfilename, 'maxRotation');
validateattributes(correctiveSpeedDegreesPerSecond, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'positive', ...
    '<=', maxDrivenRPM * kDegreesPerSecondPerRPM}, ...
    mfilename, 'correctiveSpeedDegreesPerSecond');
if mod(correctiveSpeedDegreesPerSecond, kFirmwareCorrectiveSpeedScale) ~= 0
    error(['correctiveSpeedDegreesPerSecond must be a multiple of %d deg/s ' ...
        'for the installed Due firmware.'], kFirmwareCorrectiveSpeedScale)
end
firmwareCorrectiveSpeed = ...
    correctiveSpeedDegreesPerSecond / kFirmwareCorrectiveSpeedScale;
validateattributes(correctiveKd, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative', '<=', double(intmax('uint16')) / configGainScale}, ...
    mfilename, 'correctiveKd');
validateattributes(correctiveEnable, {'numeric', 'logical'}, ...
    {'scalar', 'real', 'finite'}, mfilename, 'correctiveEnable');
if correctiveEnable ~= 0 && correctiveEnable ~= 1
    error('correctiveEnable must be false/0 or true/1.')
end
validateattributes(correctionStartDelayMs, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'nonnegative', '<=', double(intmax('uint16'))}, ...
    mfilename, 'correctionStartDelayMs');

outputActions = [outputActions, ...
    {servoMotor, uint8([ ...
        configOpCode, ...
        typecast(uint16(maxDrivenRPM), 'uint8') ...
    ])}];

sma = AddState(sma, namestr, stateName, ...
    'Timer', 1, ...
    'StateChangeConditions', {receivedInstruction, 'ServoMotorImplicitConfigState1', 'Tup', 'exit'}, ...
    outputstr, outputActions);

sma = AddState(sma, namestr, 'ServoMotorImplicitConfigState1', ...
    'Timer', 1, ...
    'StateChangeConditions', {receivedInstruction, 'ServoMotorImplicitConfigState2', 'Tup', 'exit'}, ...
    'OutputActions', {servoMotor, typecast(uint16(timeMultiplier), 'uint8')});

sma = AddState(sma, namestr, 'ServoMotorImplicitConfigState2', ...
    'Timer', 1, ...
    'StateChangeConditions', {receivedInstruction, 'ServoMotorImplicitConfigState3', 'Tup', 'exit'}, ...
    'OutputActions', {servoMotor, typecast(uint16(tolerance), 'uint8')});

sma = AddState(sma, namestr, 'ServoMotorImplicitConfigState3', ...
    'Timer', 1, ...
    'StateChangeConditions', {receivedInstruction, 'ServoMotorImplicitConfigState4', 'Tup', 'exit'}, ...
    'OutputActions', {servoMotor, typecast(uint16(encoderPPR), 'uint8')});

sma = AddState(sma, namestr, 'ServoMotorImplicitConfigState4', ...
    'Timer', 1, ...
    'StateChangeConditions', {receivedInstruction, 'ServoMotorImplicitConfigState5', 'Tup', 'exit'}, ...
    'OutputActions', {servoMotor, typecast(uint16(maxRotation), 'uint8')});

sma = AddState(sma, namestr, 'ServoMotorImplicitConfigState5', ...
    'Timer', 1, ...
    'StateChangeConditions', {receivedInstruction, 'ServoMotorImplicitConfigState6', 'Tup', 'exit'}, ...
    'OutputActions', {servoMotor, typecast(uint16(firmwareCorrectiveSpeed), 'uint8')});

sma = AddState(sma, namestr, 'ServoMotorImplicitConfigState6', ...
    'Timer', 1, ...
    'StateChangeConditions', {receivedInstruction, 'ServoMotorImplicitConfigState7', 'Tup', 'exit'}, ...
    'OutputActions', {servoMotor, typecast(uint16(round(correctiveKd * configGainScale)), 'uint8')});

sma = AddState(sma, namestr, 'ServoMotorImplicitConfigState7', ...
    'Timer', 1, ...
    'StateChangeConditions', {receivedInstruction, 'ServoMotorImplicitConfigState8', 'Tup', 'exit'}, ...
    'OutputActions', {servoMotor, typecast(uint16(correctiveEnable), 'uint8')});

sma = AddState(sma, namestr, 'ServoMotorImplicitConfigState8', ...
    'Timer', 1, ...
    conditionstr, [stateChangeConditions, {'Tup', 'exit'}], ...
    'OutputActions', {servoMotor, typecast(uint16(correctionStartDelayMs), 'uint8')});



% Bpod's implicit serial-message de-duplication can return a linear cell
% index instead of the message index within this module's UART row. Repair
% each generated config state so repeated payloads, such as uint16(1), use
% the serial-message entry that actually contains the requested bytes.
configStateNames = { ...
    stateName, ...
    'ServoMotorImplicitConfigState1', ...
    'ServoMotorImplicitConfigState2', ...
    'ServoMotorImplicitConfigState3', ...
    'ServoMotorImplicitConfigState4', ...
    'ServoMotorImplicitConfigState5', ...
    'ServoMotorImplicitConfigState6', ...
    'ServoMotorImplicitConfigState7', ...
    'ServoMotorImplicitConfigState8'};
configMessages = { ...
    uint8([configOpCode, typecast(uint16(maxDrivenRPM), 'uint8')]), ...
    typecast(uint16(timeMultiplier), 'uint8'), ...
    typecast(uint16(tolerance), 'uint8'), ...
    typecast(uint16(encoderPPR), 'uint8'), ...
    typecast(uint16(maxRotation), 'uint8'), ...
    typecast(uint16(firmwareCorrectiveSpeed), 'uint8'), ...
    typecast(uint16(round(correctiveKd * configGainScale)), 'uint8'), ...
    typecast(uint16(correctiveEnable), 'uint8'), ...
    typecast(uint16(correctionStartDelayMs), 'uint8')};
sma = repairImplicitSerialOutputs(sma, configStateNames, servoMotor, configMessages);

ServoMotorStruct.maxRotation = maxRotation;
ServoMotorStruct.timeMultiplier = timeMultiplier;
ServoMotorStruct.maxDrivenRPM = maxDrivenRPM;
sma_out = sma;

end

function sma = repairImplicitSerialOutputs(sma, stateNames, outputName, messages)
global BpodSystem

outputChannel = find(strcmp(outputName, BpodSystem.StateMachineInfo.OutputChannelNames), 1);
if isempty(outputChannel)
    error('Unable to find output channel %s.', outputName)
end

for stateNumber = 1:numel(stateNames)
    stateIndex = find(strcmp(stateNames{stateNumber}, sma.StateNames), 1);
    if isempty(stateIndex)
        error('Unable to find generated config state %s.', stateNames{stateNumber})
    end

    expectedMessage = uint8(messages{stateNumber});
    correctMessageIndex = [];
    for messageIndex = 1:sma.nSerialMessages(outputChannel)
        if isequal(sma.SerialMessages{outputChannel, messageIndex}, expectedMessage)
            correctMessageIndex = messageIndex;
            break
        end
    end

    if isempty(correctMessageIndex)
        error('Unable to find the implicit serial message for state %s.', stateNames{stateNumber})
    end
    sma.OutputMatrix(stateIndex, outputChannel) = correctMessageIndex;
end
end
