function message = getEncoderConfig(triggerSpeedMmPerSecond, integrationPeriodMs)

validateattributes(triggerSpeedMmPerSecond, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'nonnegative', '<=', 1000}, ...
    mfilename, 'triggerSpeedMmPerSecond');
validateattributes(integrationPeriodMs, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'nonnegative', ...
    '<=', double(intmax('uint16'))}, ...
    mfilename, 'integrationPeriodMs');

configureSpeedTriggerOpCode = uint8(1);
message = uint8([ ...
    configureSpeedTriggerOpCode, ...
    typecast(uint16(triggerSpeedMmPerSecond), 'uint8'), ...
    typecast(uint16(integrationPeriodMs), 'uint8') ...
]);

end
