global ServoMotorStruct

ServoMotorStruct = struct('instructedRotation', 0, ...
    'maxRotation', 720, ...
    'maxDrivenRPM', 120, ...
    'timeMultiplier', 1, ...
    'isEnabled', false, ...
    'homedInTrial', false);

global ServoMotorInstructions

ServoMotorInstructions = ones(1, 100);
