; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
test_dir = MainArduinoDue/test

; ─────────────────────────────────────────────
; Arduino Due through programming USB port
; ─────────────────────────────────────────────

[env:due]

platform = atmelsam

board = due

framework = arduino

build_src_filter =

    -<*>

    +<MainArduinoDue/src/test.cpp>

    +<MainArduinoDue/src/ArCom/*.cpp>

build_flags =

    -I MainArduinoDue/include

platform_packages =

    tool-bossac@~1.10901.0

upload_protocol = sam-ba

upload_port = /dev/cu.usbmodem*

upload_command = bash -c 'for i in {1..5}; do "$UPLOADER" --port="$UPLOAD_PORT" --usb-port=false -e -w -v -b "$SOURCE" -R && exit 0; sleep 1; done; exit 1'

monitor_speed = 115200

monitor_echo = yes

; ─────────────────────────────────────────────
; Arduino Due through native USB port
; ─────────────────────────────────────────────

[env:dueUSB]
platform = atmelsam
board = dueUSB
framework = arduino
monitor_speed = 115200

build_src_filter =

    -<*>

    +<MainArduinoDue/src/*.cpp>

    +<MainArduinoDue/src/ArCom/*.cpp>

build_flags =
    -IMainArduinoDue/include

lib_extra_dirs =
    MainArduinoDue/lib

test_framework = unity

test_speed = 115200


; ─────────────────────────────────────────────
; Arduino Nano ESP32 safety controller
; ─────────────────────────────────────────────

[env:safetyNanoESP32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed = 115200

build_src_filter =
    -<*>
    +<SafetyArduinoNano/src/>

build_flags =
    -ISafetyArduinoNano/include

lib_extra_dirs =
    SafetyArduinoNano/lib

; ─────────────────────────────────────────────
; Bpod Rotary Encoder Module v1 on Arduino Nano ESP32
; ─────────────────────────────────────────────

[env:rotaryEncoderNanoESP32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed = 115200

build_src_filter =
    -<*>
    +<RotaryEncoderArduinoNano/src/>

build_flags =
    -IRotaryEncoderArduinoNano/include

lib_extra_dirs =
    RotaryEncoderArduinoNano/lib
