; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
test_dir = MainArduinoDue/test

; ─────────────────────────────────────────────
; Arduino Due through programming USB port
; ─────────────────────────────────────────────

[env:due]
platform = atmelsam
board = due
framework = arduino
monitor_speed = 115200

build_src_filter =
    -<*>
    +<MainArduinoDue/src/>

build_flags =
    -IMainArduinoDue/include

lib_extra_dirs =
    MainArduinoDue/lib


; ─────────────────────────────────────────────
; Arduino Due through native USB port
; ─────────────────────────────────────────────

[env:dueUSB]
platform = atmelsam
board = dueUSB
framework = arduino
monitor_speed = 115200

upload_port = /dev/cu.usbmodem101

build_src_filter =
    -<*>
    +<MainArduinoDue/src/>

build_flags =
    -IMainArduinoDue/include

lib_extra_dirs =
    MainArduinoDue/lib

test_framework = unity

test_speed = 115200


; ─────────────────────────────────────────────
; Arduino Nano ESP32 safety controller
; ─────────────────────────────────────────────

[env:safetyNanoESP32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed = 115200

build_src_filter =
    -<*>
    +<SafetyArduinoNano/src/>

build_flags =
    -ISafetyArduinoNano/include

lib_extra_dirs =
    SafetyArduinoNano/lib